openapi: 3.0.0
info:
  title: PDF Editors API
  version: 1.0.0
  description: API for various PDF editing operations
servers:
  - url: http://localhost:5000
paths:
  /split:
    post:
      summary: Split PDF pages
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully split PDF pages
  /marge:
    post:
      summary: Marge PDF pages
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: Successfully merged PDF pages
  /delete:
    post:
      summary: Delete PDF pages
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                pages:
                  type: string
      responses:
        '200':
          description: Successfully deleted PDF pages
  /extract:
    post:
      summary: Extract PDF pages
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                pages:
                  type: string
      responses:
        '200':
          description: Successfully extracted PDF pages
  /rotate:
    post:
      summary: Rotate PDF pages
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                angle:
                  type: integer
      responses:
        '200':
          description: Successfully rotated PDF pages
  /extract_text:
    post:
      summary: Extract text from PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully extracted text from PDF
  /extract_image:
    post:
      summary: Extract images from PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully extracted images from PDF
  /extract_table:
    post:
      summary: Extract tables from PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully extracted tables from PDF
  /convert_image:
    post:
      summary: Convert PDF to Image
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully converted PDF to Image
  /convert_docx:
    post:
      summary: Convert PDF to Word
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully converted PDF to Word